export const location = {
  VIE: [
    { id: 1, text: "Hồ Chí Minh", value: "1" },
    { id: 2, text: "Hà Nội", value: "2" },
    { id: 3, text: "Đà Nẵng", value: "3" },
    { id: 4, text: "Huế", value: "4" },
    { id: 5, text: "Đồng Nai", value: "5" },
    { id: 6, text: "Khánh Hòa", value: "6" },
    { id: 7, text: "Hải Phòng", value: "7" },
    { id: 8, text: "Quảng Nam", value: "8" },
    { id: 9, text: "Bà Rịa-Vũng Tàu", value: "9" },
    { id: 10, text: "Đắk Lắk", value: "10" },
    { id: 11, text: "Cần Thơ", value: "11" },
    { id: 12, text: "Bình Thuận", value: "12" },
    { id: 13, text: "Lâm Đồng", value: "13" },
    { id: 14, text: "Bình Dương", value: "14" },
    { id: 15, text: "Kiên Giang", value: "15" },
    { id: 16, text: "Bắc Ninh", value: "16" },
    { id: 17, text: "Quảng Ninh", value: "17" },
    { id: 18, text: "Thanh Hóa", value: "18" },
    { id: 19, text: "Nghệ An", value: "19" },
    { id: 20, text: "Hải Dương", value: "20" },
    { id: 21, text: "Gia Lai", value: "21" },
    { id: 22, text: "Bình Phước", value: "22" },
    { id: 23, text: "Hưng Yên", value: "23" },
    { id: 24, text: "Bình Định", value: "24" },
    { id: 25, text: "Tiền Giang", value: "25" },
    { id: 26, text: "Thái Bình", value: "26" },
    { id: 27, text: "Bắc Giang", value: "27" },
    { id: 28, text: "Hòa Bình", value: "28" },
    { id: 29, text: "An Giang", value: "29" },
    { id: 30, text: "Vĩnh Phúc", value: "30" },
    { id: 31, text: "Tây Ninh", value: "31" },
    { id: 32, text: "Thái Nguyên", value: "32" },
    { id: 33, text: "Lào Cai", value: "33" },
    { id: 34, text: "Nam Định", value: "34" },
    { id: 35, text: "Bến Tre", value: "35" },
    { id: 36, text: "Đắk Nông", value: "36" },
    { id: 37, text: "Cà Mau", value: "37" },
    { id: 38, text: "Vĩnh Long", value: "38" },
    { id: 39, text: "Ninh Bình", value: "39" },
    { id: 40, text: "Phú Thọ", value: "40" },
    { id: 41, text: "Ninh Thuận", value: "41" },
    { id: 42, text: "Phú Yên", value: "42" },
    { id: 43, text: "Hà Nam", value: "43" },
    { id: 44, text: "Hà Tĩnh", value: "44" },
    { id: 45, text: "Đồng Tháp", value: "45" },
    { id: 46, text: "Sóc Trăng", value: "46" },
    { id: 47, text: "Kon Tum", value: "47" },
    { id: 48, text: "Quảng Trị", value: "48" },
    { id: 49, text: "Trà Vinh", value: "49" },
    { id: 50, text: "Hậu Giang", value: "50" },
    { id: 51, text: "Sơn La", value: "51" },
    { id: 52, text: "Bạc Liêu", value: "52" },
    { id: 53, text: "Yên Bái", value: "53" },
    { id: 54, text: "Tuyên Quang", value: "54" },
    { id: 55, text: "Điện Biên", value: "55" },
    { id: 56, text: "Lai Châu", value: "56" },
    { id: 57, text: "Lạng Sơn", value: "57" },
    { id: 58, text: "Hà Giang", value: "58" },
    { id: 59, text: "Bắc Kạn", value: "59" },
    { id: 60, text: "Cao Bằng", value: "60" },
    { id: 61, text: "Long An", value: "61" },
    { id: 62, text: "Quảng Bình", value: "62" },
    { id: 63, text: "Quảng Ngãi", value: "63" },
  ],
};
